import java.io.*; // for handling input/output
import java.util.*; // contains Collections framework

public class NS_palindices {
    /*Generated by Newton AI.
    To count the number of indices i, the code checks whether n is even or odd to check whether to process the input string. 
    If n is even, it extracts the first half of the string, and counts the number of letters that are the same from the center of the odd string. 
    If n is odd, the code counts the number of letters that are the same in the two halves of the even string. 
    Return the count of indices i. The next two steps are to store the number of indices i in a variable and return it at the end of the code. */
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        if(n%2==0){
            String s=sc.next().substring(0, n/2);
            int i=n/2-1,count=1;
            while(i>0 && s.charAt(i)==s.charAt(i-1)){
                count++;
                i--;
            }
            System.out.println(count*2);
        }
        else{
            String s=sc.next(),s1=s.substring(0, n/2),s2=s.substring(n/2,n/2+1);
            int i=n/2-1,count=0;
            while(i>=0 && s1.charAt(i)==s2.charAt(0)){
                count++;
                i--;
            }
            System.out.println(count*2+1);
        }sc.close();
    }
}
